version: '3.7'

services:    
  web:
    build:
      context: frontend/
      dockerfile: ./Dockerfile
    working_dir: /usr/src/dsc_app/frontend/
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - REACT_APP_API=localhost:8080/

  api:
    # image: cloud_app
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src/dsc_app/backend/
    command: sh -c "alembic -c ./v1/alembic_prod.ini upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/dsc_app/
      - nfs-volume:/usr/src/dsc_app/storage
    env_file:
      - ./.env.prod
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - TZ=America/Bogota
      - BD_URI=postgresql+psycopg2://postgres:postgres@10.0.0.3/dsc
      - ALEMBIC_CONFIG=v1/alembic_prod.ini
    cpus: 1
    mem_limit: 1150m
    ports:
      - 8080:8080
    

volumes: 
  nfs-volume: 
    driver_opts: 
      type: "nfs" 
      o: "addr=10.128.0.4,nfsvers=4"
      device: ":/home/d_pinedae/storage"