version: '3.7'

services:    
  db:
      image: postgres:15.2-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=dsc
      ports:
        - 5432:5432
      volumes: 
        - ./postgresql/data/:/var/lib/postgresql/data