version: '3.7'

services:    
  pubsub:
    # image: cloud_app
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src/dsc_app/backend/
    command: sh -c "python pubsub.py"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/dsc_app/
    env_file:
      - ./.env.prod
    depends_on:
          - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - TZ=America/Bogota
      - BD_URI=postgresql+psycopg2://postgres:postgres@10.0.0.3/dsc
      - ALEMBIC_CONFIG=v1/alembic_prod.ini
      - CELERY_BROKER_URL=amqp://cloud_user:cloud_user@rabbitmq:5672//
    cpus: 1
    mem_limit: 1024m
      